blank_issues_enabled: false
contact_links:
  - name: Visit the website for information about installing and using
    about: Here there is general-purpose information about VoxelEarth.
    url: https://voxelearth.org

  - name: Join our Discord for questions 
    about: Take a look in our Discord to meet and talk with our friendly community or ask questions in the /#help section for support.
    url: https://discord.com/invite/8MK8J9EQGe